apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange
  namespace: default
  labels:
    app: currency-exchange
spec:
  replicas: 2
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
      - name: currency-exchange-service
        image: ashekharr/currency-exchange-service:0.0.1-Kubernetes
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: currency-exchange
  namespace: default
  labels:
    app: currency-exchange
spec:
  type: LoadBalancer
  selector:
    app: currency-exchange
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
