apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-08-01T09:00:24Z"
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "8384"
  uid: cc9c9518-168f-4c71-91fa-d847c08c86f0
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.105.202.210
  clusterIPs:
  - 10.105.202.210
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32242
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: currency-exchange
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
