apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion
  namespace: default
  labels:
    app: currency-conversion
spec:
  replicas: 2
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - name: currency-conversion-service
        image: ashekharr/currency-conversion-service:0.0.2-Kubernetes
        imagePullPolicy: IfNotPresent
        env:
          - name: CURRENCY_EXCHANGE_URI
            value: http://currency-exchange
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: currency-conversion
  namespace: default
  labels:
    app: currency-conversion
spec:
  type: LoadBalancer
  selector:
    app: currency-conversion
  ports:
  - port: 8100
    targetPort: 8100
    protocol: TCP
